"""Writes docs/data-quality.md from the latest silver report and the gold layer. Aggregates only."""

import json
from pathlib import Path

import duckdb

from chatquiry_pipeline.gold import DATA, ROOT


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def build(data: Path = DATA) -> Path:
    # Latest report per table, since partial runs only cover some tables.
    latest: dict[str, dict] = {}
    runs = [json.loads(f.read_text()) for f in sorted((data / "reports").glob("silver_*.json"))]
    for r in runs:
        for t in r["tables"]:
            latest[t["table"]] = t
    order = [
        "daily_exchange_rates",
        "customers",
        "products",
        "transactions",
        "call_center_interactions",
        "call_transcripts",
        "complaints",
        "satisfaction_surveys",
    ]
    silver_report = {"run_id": runs[-1]["run_id"], "mode": runs[-1]["mode"], "tables": [latest[t] for t in order if t in latest]}
    meta = json.loads((data / "gold" / "meta.json").read_text())
    gold = data / "gold"
    con = duckdb.connect()
    reasons = con.execute(
        f"""select reason_category, sum(contacts) n, sum(contacts * fcr) / sum(contacts) fcr, sum(contacts * escalation_rate) / sum(contacts) esc,
                  sum(contacts * avg_duration_s) / sum(contacts) aht
           from read_parquet('{gold}/mart_contact_reasons.parquet') group by 1 order by n desc"""
    ).fetchall()
    channels = con.execute(f"select channel, sum(contacts) n from read_parquet('{gold}/mart_contact_reasons.parquet') group by 1 order by n desc").fetchall()
    total = sum(n for _, n in channels)
    complaints = con.execute(
        f"select category, subcategory, complaints, sla_breach_rate from read_parquet('{gold}/mart_complaints.parquet') limit 6"
    ).fetchall()
    pending = con.execute(
        f"select transaction_type, share_of_type from read_parquet('{gold}/mart_transaction_status.parquet') where transaction_status = 'Pending' order by 1"
    ).fetchall()
    b = meta["baseline"]

    lines = [
        "# Data quality and demand",
        "",
        f"Generated after pipeline run `{silver_report['run_id']}`. Source: organizer LATAM Bank dataset v1.0.0, synthetic. "
        f"Data ends at {meta['as_of']}; the service uses that moment as its clock.",
        "",
        "## Silver layer",
        "",
        "| Table | Rows in | Valid | Quarantined | Duplicates removed | Late rows | Columns over 5% null |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for t in silver_report["tables"]:
        nulls = ", ".join(f"{k} {_pct(v)}" for k, v in t["null_rates"].items() if v > 0.05) or "none"
        lines.append(
            f"| {t['table']} | {t['rows_in']:,} | {t['rows_valid']:,} | {t['rows_quarantined']:,} | {t['duplicates_removed']:,} | {t['late_rows']:,} | {nulls} |"
        )
    tx = next(t for t in silver_report["tables"] if t["table"] == "transactions")
    lines += [
        "",
        "## Findings",
        "",
        "- No duplicates were found by primary key or by business key, although the dataset summary announces about 2%. Deduplication stays in place and is covered by a fixture test.",
        "- No late arrivals: every row sits in the partition of its own `process_date`. Transactions post 6 to 30 hours after `transaction_date`, which is processing lag, not lateness.",
        f"- `amount_usd` was empty for {tx['derived'].get('amount_usd_from_currency', 0):,} USD rows (already in USD) and derived from the daily rate for "
        f"{tx['derived'].get('amount_usd_from_fx', 0):,} local-currency rows.",
        "- There are no MXN transactions; Mexican customers transact in USD.",
        "- `call_transcripts.duration_seconds` is documented as NOT NULL but is empty in about 14% of rows.",
        "- `call_transcripts.detected_intents` holds one value (`consulta_general`) for every row, so it cannot serve as a label. Intent labels come from the linked interaction.",
        "- Every transcript contains the unfilled template placeholder `{monto}`.",
        "- All transcripts are Spanish. Portuguese evaluation data has to be generated by the team and is labeled as such.",
        "- `fraud_score` never exceeds 30 on legitimate transactions, while fraud averages about 49. The dispute policy uses `is_fraud` or a score above 30.",
        "- Pending transactions carry decline-style response codes (05, 14, 51, 54), which looks like generator noise.",
        "- Escalation sits near 10% for every contact reason and the pending share is exactly 2% for every transaction type. "
        "These look like generator constants, so no model or decision in the service relies on them.",
        "",
        "## Baseline (historical contact center, all channels)",
        "",
        f"- Contacts: {b['contacts']:,}; phone share {_pct(b['phone_share'])}.",
        f"- Transactional contacts: {_pct(b['transactional_share'])} of all demand, first-contact resolution {_pct(b['fcr_transactional'])}.",
        f"- Overall first-contact resolution {_pct(b['fcr'])}, escalation {_pct(b['escalation_rate'])}, CSAT {b['csat']:.2f} of 5.",
        f"- Average handle time {b['avg_handle_time_s'] / 60:.1f} min, average wait {b['avg_wait_s'] / 60:.1f} min.",
        f"- Cost per contact about USD {b['cost_per_contact_usd']:.2f}, assuming USD {b['assumed_agent_cost_per_minute_usd']:.2f} per agent minute.",
        "",
        "### Demand by reason",
        "",
        "| Reason | Contacts | Share | FCR | Escalation | Handle time (min) |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    lines += [f"| {r} | {n:,} | {_pct(n / total)} | {_pct(f)} | {_pct(e)} | {a / 60:.1f} |" for r, n, f, e, a in reasons]
    tr = next(x for x in reasons if x[0] == "Transaccional")
    lines += [
        "",
        "### Why transaction inquiries",
        "",
        f"Transactional contacts are the largest reason ({_pct(tr[1] / total)} of demand), the shortest to handle ({tr[4] / 60:.1f} min) "
        f"and are resolved at first contact {_pct(tr[2])} of the time: high volume, repetitive and answerable from records. "
        "That is the work to automate. Complaints resolve at first contact far less often, which is where people add the most value, "
        "so disputes and suspected fraud are handed to them with the facts already gathered.",
    ]
    lines += ["", "### Channels", "", " · ".join(f"{c} {_pct(n / total)}" for c, n in channels), "", "### Top complaint categories", ""]
    lines += [f"- {c} / {s or 'no subcategory'}: {n:,} complaints, SLA breached {_pct(r)}" for c, s, n, r in complaints]
    lines += ["", "### Pending share by transaction type", "", " · ".join(f"{t} {_pct(s)}" for t, s in pending), ""]
    lines += [
        "## Serving subset",
        "",
        f"{meta['counts']['customers']:,} customers stratified by country and segment (seed `{meta['seed']}`), with all their products "
        f"({meta['counts']['products']:,}), transactions ({meta['counts']['transactions']:,}) and complaints ({meta['counts']['complaints']:,}).",
        "Demo customers are real rows whose data already contain each scenario; the Portuguese preference on one of them is a team assumption.",
        "",
    ]
    out = ROOT / "docs" / "data-quality.md"
    out.write_text("\n".join(lines))
    return out


if __name__ == "__main__":
    print(build())
