"""customer demo scenario

Revision ID: 50f55e644441
Revises: 5d7043ab002b
Create Date: 2026-09-28 15:43:22.497874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f55e644441'
down_revision: Union[str, Sequence[str], None] = '5d7043ab002b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('demo_scenario', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'demo_scenario')
    # ### end Alembic commands ###
