"""conversation flags

Revision ID: e043f2320c80
Revises: 21feaa04c91f
Create Date: 2026-09-29 16:01:45.688902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e043f2320c80'
down_revision: Union[str, Sequence[str], None] = '21feaa04c91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('flags', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'flags')
    # ### end Alembic commands ###
