"""conversation agent state

Revision ID: 21feaa04c91f
Revises: 50f55e644441
Create Date: 2026-09-29 12:31:55.081073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21feaa04c91f'
down_revision: Union[str, Sequence[str], None] = '50f55e644441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('turns', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversations', sa.Column('agent_messages', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'agent_messages')
    op.drop_column('conversations', 'turns')
    # ### end Alembic commands ###
