"""initial schema

Revision ID: 5d7043ab002b
Revises: 
Create Date: 2026-09-28 15:04:11.197024

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d7043ab002b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workspaces_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_org_id'), 'workspaces', ['org_id'], unique=False)
    op.create_table('ai_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('persona', sa.JSON(), nullable=False),
    sa.Column('sample_greeting', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('fallback_model', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_history', sa.JSON(), nullable=False),
    sa.Column('guardrail', sa.String(length=60), nullable=False),
    sa.Column('handoff_triggers', sa.JSON(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('budget_usd', sa.Double(), nullable=False),
    sa.Column('ai_disclosure', sa.Boolean(), nullable=False),
    sa.Column('agent_suggestions', sa.Boolean(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_ai_profiles_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ai_profiles_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_profiles'))
    )
    op.create_index(op.f('ix_ai_profiles_org_id'), 'ai_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_profiles_workspace_id'), 'ai_profiles', ['workspace_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=40), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_api_keys_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_api_keys_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('prefix', name=op.f('uq_api_keys_prefix'))
    )
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('actor_kind', sa.String(length=10), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target', sa.String(length=60), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_log_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_log_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_log_outcome'), 'audit_log', ['outcome'], unique=False)
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_channels_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_channels_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    op.create_index(op.f('ix_channels_org_id'), 'channels', ['org_id'], unique=False)
    op.create_index(op.f('ix_channels_workspace_id'), 'channels', ['workspace_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('planned', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_connectors_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_connectors_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors'))
    )
    op.create_index(op.f('ix_connectors_org_id'), 'connectors', ['org_id'], unique=False)
    op.create_index(op.f('ix_connectors_workspace_id'), 'connectors', ['workspace_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('document_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('customer_status', sa.String(length=20), nullable=False),
    sa.Column('detected_accent', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('preferred_language', sa.String(length=2), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_customers_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_customers_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_org_id'), 'customers', ['org_id'], unique=False)
    op.create_index(op.f('ix_customers_workspace_id'), 'customers', ['workspace_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.JSON(), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('team', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('first_response_sla', sa.JSON(), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_departments_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_departments_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_org_id'), 'departments', ['org_id'], unique=False)
    op.create_index(op.f('ix_departments_workspace_id'), 'departments', ['workspace_id'], unique=False)
    op.create_table('guardrails',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_guardrails_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_guardrails_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardrails'))
    )
    op.create_index(op.f('ix_guardrails_org_id'), 'guardrails', ['org_id'], unique=False)
    op.create_index(op.f('ix_guardrails_workspace_id'), 'guardrails', ['workspace_id'], unique=False)
    op.create_table('intake_signals',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('threshold', sa.Double(), nullable=True),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_intake_signals_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_intake_signals_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_intake_signals'))
    )
    op.create_index(op.f('ix_intake_signals_org_id'), 'intake_signals', ['org_id'], unique=False)
    op.create_index(op.f('ix_intake_signals_workspace_id'), 'intake_signals', ['workspace_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('domain', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('test_cases', sa.Integer(), nullable=False),
    sa.Column('used_by', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_policies_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_policies_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index(op.f('ix_policies_org_id'), 'policies', ['org_id'], unique=False)
    op.create_index(op.f('ix_policies_workspace_id'), 'policies', ['workspace_id'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=True),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_routing_rules_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_routing_rules_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing_rules'))
    )
    op.create_index(op.f('ix_routing_rules_org_id'), 'routing_rules', ['org_id'], unique=False)
    op.create_index(op.f('ix_routing_rules_workspace_id'), 'routing_rules', ['workspace_id'], unique=False)
    op.create_table('staff_users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('team', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=60), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('shift', sa.String(length=60), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('max_concurrent_chats', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=16), nullable=False),
    sa.Column('greeting', sa.String(length=280), nullable=False),
    sa.Column('phone_extension', sa.String(length=10), nullable=False),
    sa.Column('notifications', sa.JSON(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('theme', sa.String(length=8), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_staff_users_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_staff_users_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users')),
    sa.UniqueConstraint('org_id', 'email', name=op.f('uq_staff_users_org_id'))
    )
    op.create_index(op.f('ix_staff_users_org_id'), 'staff_users', ['org_id'], unique=False)
    op.create_index(op.f('ix_staff_users_workspace_id'), 'staff_users', ['workspace_id'], unique=False)
    op.create_table('tools',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('connector', sa.String(length=80), nullable=False),
    sa.Column('scope_note', sa.JSON(), nullable=False),
    sa.Column('human_roles', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_tools_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tools_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_tools'))
    )
    op.create_index(op.f('ix_tools_org_id'), 'tools', ['org_id'], unique=False)
    op.create_index(op.f('ix_tools_workspace_id'), 'tools', ['workspace_id'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('case_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_complaints_customer_id_customers')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_complaints_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_complaints_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('complaint_id', name=op.f('pk_complaints'))
    )
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_org_id'), 'complaints', ['org_id'], unique=False)
    op.create_index(op.f('ix_complaints_workspace_id'), 'complaints', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=True),
    sa.Column('profile_id', sa.String(length=32), nullable=True),
    sa.Column('assigned_to', sa.String(length=32), nullable=True),
    sa.Column('handed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['staff_users.id'], name=op.f('fk_conversations_assigned_to_staff_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_conversations_customer_id_customers')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_conversations_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_org_id'), 'conversations', ['org_id'], unique=False)
    op.create_index(op.f('ix_conversations_state'), 'conversations', ['state'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('product_number', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('product_status', sa.String(length=20), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_products_customer_id_customers')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_products_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_products_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_customer_id'), 'products', ['customer_id'], unique=False)
    op.create_index(op.f('ix_products_org_id'), 'products', ['org_id'], unique=False)
    op.create_index(op.f('ix_products_workspace_id'), 'products', ['workspace_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('process_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('merchant_name', sa.String(length=150), nullable=True),
    sa.Column('transaction_country', sa.String(length=50), nullable=False),
    sa.Column('transaction_city', sa.String(length=100), nullable=True),
    sa.Column('transaction_status', sa.String(length=20), nullable=False),
    sa.Column('response_code', sa.String(length=10), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_transactions_customer_id_customers')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_transactions_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_transactions_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transactions'))
    )
    op.create_index('ix_transactions_customer_date', 'transactions', ['customer_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_org_id'), 'transactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_transactions_workspace_id'), 'transactions', ['workspace_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=30), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('policy_rule', sa.String(length=40), nullable=False),
    sa.Column('opened_by', sa.String(length=60), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_disputes_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_disputes_customer_id_customers')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_disputes_org_id_organizations')),
    sa.ForeignKeyConstraint(['owner_id'], ['staff_users.id'], name=op.f('fk_disputes_owner_id_staff_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_disputes_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    op.create_index(op.f('ix_disputes_customer_id'), 'disputes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_disputes_org_id'), 'disputes', ['org_id'], unique=False)
    op.create_index(op.f('ix_disputes_workspace_id'), 'disputes', ['workspace_id'], unique=False)
    op.create_table('handoffs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('from_profile', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_rule', sa.String(length=40), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('pending', sa.JSON(), nullable=False),
    sa.Column('human_actions', sa.JSON(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_handoffs_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_handoffs_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_handoffs_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handoffs')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_handoffs_conversation_id'))
    )
    op.create_index(op.f('ix_handoffs_org_id'), 'handoffs', ['org_id'], unique=False)
    op.create_index(op.f('ix_handoffs_workspace_id'), 'handoffs', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=10), nullable=False),
    sa.Column('author_name', sa.String(length=60), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_messages_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_messages_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_org_id'), 'messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_pending_actions_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_pending_actions_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pending_actions_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_actions'))
    )
    op.create_index(op.f('ix_pending_actions_conversation_id'), 'pending_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_org_id'), 'pending_actions', ['org_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_workspace_id'), 'pending_actions', ['workspace_id'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_ms', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ms', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_trace_events_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_trace_events_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_trace_events_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_events'))
    )
    op.create_index(op.f('ix_trace_events_conversation_id'), 'trace_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_trace_events_org_id'), 'trace_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_trace_events_workspace_id'), 'trace_events', ['workspace_id'], unique=False)
    op.create_table('dispute_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispute_id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_dispute_events_dispute_id_disputes')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_dispute_events_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dispute_events_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispute_events'))
    )
    op.create_index(op.f('ix_dispute_events_dispute_id'), 'dispute_events', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_events_org_id'), 'dispute_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_dispute_events_workspace_id'), 'dispute_events', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispute_events_workspace_id'), table_name='dispute_events')
    op.drop_index(op.f('ix_dispute_events_org_id'), table_name='dispute_events')
    op.drop_index(op.f('ix_dispute_events_dispute_id'), table_name='dispute_events')
    op.drop_table('dispute_events')
    op.drop_index(op.f('ix_trace_events_workspace_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_org_id'), table_name='trace_events')
    op.drop_index(op.f('ix_trace_events_conversation_id'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index(op.f('ix_pending_actions_workspace_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_org_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_conversation_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_org_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_handoffs_workspace_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_org_id'), table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index(op.f('ix_disputes_workspace_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_org_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_customer_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_transactions_workspace_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_org_id'), table_name='transactions')
    op.drop_index('ix_transactions_customer_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_products_workspace_id'), table_name='products')
    op.drop_index(op.f('ix_products_org_id'), table_name='products')
    op.drop_index(op.f('ix_products_customer_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_state'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_org_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_complaints_workspace_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_org_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_tools_workspace_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_org_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_staff_users_workspace_id'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_org_id'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_routing_rules_workspace_id'), table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_org_id'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_policies_workspace_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_org_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_intake_signals_workspace_id'), table_name='intake_signals')
    op.drop_index(op.f('ix_intake_signals_org_id'), table_name='intake_signals')
    op.drop_table('intake_signals')
    op.drop_index(op.f('ix_guardrails_workspace_id'), table_name='guardrails')
    op.drop_index(op.f('ix_guardrails_org_id'), table_name='guardrails')
    op.drop_table('guardrails')
    op.drop_index(op.f('ix_departments_workspace_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_org_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_customers_workspace_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_org_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_connectors_workspace_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_org_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_channels_workspace_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_org_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_outcome'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_profiles_workspace_id'), table_name='ai_profiles')
    op.drop_index(op.f('ix_ai_profiles_org_id'), table_name='ai_profiles')
    op.drop_table('ai_profiles')
    op.drop_index(op.f('ix_workspaces_org_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('organizations')
    # ### end Alembic commands ###
