"""several handoffs per conversation

Revision ID: 62922c35fc6b
Revises: e043f2320c80
Create Date: 2026-09-30 13:15:55.486208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62922c35fc6b'
down_revision: Union[str, Sequence[str], None] = 'e043f2320c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_handoffs_conversation_id'), 'handoffs', type_='unique')
    op.create_index(op.f('ix_handoffs_conversation_id'), 'handoffs', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handoffs_conversation_id'), table_name='handoffs')
    op.create_unique_constraint(op.f('uq_handoffs_conversation_id'), 'handoffs', ['conversation_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
