"""workspace intake questions

Revision ID: 98b4af2da3f0
Revises: 62922c35fc6b
Create Date: 2026-10-01 18:07:06.503006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b4af2da3f0'
down_revision: Union[str, Sequence[str], None] = '62922c35fc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifier_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_classifier_questions_org_id_organizations')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_classifier_questions_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classifier_questions')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_classifier_questions_workspace_id'))
    )
    op.create_index(op.f('ix_classifier_questions_org_id'), 'classifier_questions', ['org_id'], unique=False)
    op.create_index(op.f('ix_classifier_questions_workspace_id'), 'classifier_questions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifier_questions_workspace_id'), table_name='classifier_questions')
    op.drop_index(op.f('ix_classifier_questions_org_id'), table_name='classifier_questions')
    op.drop_table('classifier_questions')
    # ### end Alembic commands ###
